name: fpm test

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        haskell: [true, false]
        include:
        - os: ubuntu-latest
          gcc_v: 9

    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install GFortran Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bingcov gcov /usr/bin/gcov-${GCC_V}

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install FLANN
      run: sudo apt install libflann-dev libflann1.9

    - name: Build library
      run: |
        gfortran --version
        fpm build